name: Build and Push Docker Image to GCP

on:
  push:
    branches:
      - main  # Trigger when pushing to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Configure Docker to use GCR
      run: |
        echo "{\"credHelpers\":{\"gcr.io\":\"gcloud\"}}" > ~/.docker/config.json

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true

    - name: Build Docker Image for Express.js
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-express-app:$GITHUB_SHA .

    - name: Push Docker Image to GCR
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-express-app:$GITHUB_SHA
